const urlIcons = [
    {
        id: "0",
        url: "icons/avatar/avatar1000.svg"
    }, {
        id: "1",
        url: "icons/avatar/avatar1001.svg"
    }, {
        id: "2",
        url: "icons/avatar/avatar1002.svg"
    }, {
        id: "3",
        url: "icons/avatar/avatar1003.svg"
    }, {
        id: "4",
        url: "icons/avatar/avatar1004.svg"
    }, {
        id: "5",
        url: "icons/avatar/avatar1005.svg"
    }, {
        id: "6",
        url: "icons/avatar/avatar1006.svg"
    }, {
        id: "7",
        url: "icons/avatar/avatar1007.svg"
    }, {
        id: "8",
        url: "icons/avatar/avatar1008.svg"
    }, {
        id: "9",
        url: "icons/avatar/avatar1009.svg"
    }, {
        id: "10",
        url: "icons/avatar/avatar1010.svg"
    }, {
        id: "11",
        url: "icons/avatar/avatar1011.svg"
    }, {
        id: "12",
        url: "icons/avatar/avatar1012.svg"
    }, {
        id: "13",
        url: "icons/avatar/avatar1013.svg"
    }, {
        id: "14",
        url: "icons/avatar/avatar1014.svg"
    }, {
        id: "15",
        url: "icons/avatar/avatar1015.svg"
    }, {
        id: "16",
        url: "icons/avatar/avatar1016.svg"
    }, {
        id: "17",
        url: "icons/avatar/avatar1017.svg"
    }, {
        id: "18",
        url: "icons/avatar/avatar1018.svg"
    }, {
        id: "19",
        url: "icons/avatar/avatar1019.svg"
    }, {
        id: "20",
        url: "icons/avatar/avatar1020.svg"
    }, {
        id: "21",
        url: "icons/avatar/avatar1021.svg"
    }, {
        id: "22",
        url: "icons/avatar/avatar1022.svg"
    }, {
        id: "23",
        url: "icons/avatar/avatar1023.svg"
    }, {
        id: "24",
        url: "icons/avatar/avatar1024.svg"
    }, {
        id: "25",
        url: "icons/avatar/avatar1025.svg"
    }, {
        id: "26",
        url: "icons/avatar/avatar1026.svg"
    }, {
        id: "27",
        url: "icons/avatar/avatar1027.svg"
    }, {
        id: "28",
        url: "icons/avatar/avatar1028.svg"
    }, {
        id: "29",
        url: "icons/avatar/avatar1029.svg"
    }, {
        id: "30",
        url: "icons/avatar/avatar1030.svg"
    }, {
        id: "31",
        url: "icons/avatar/avatar1031.svg"
    }, {
        id: "32",
        url: "icons/avatar/avatar1032.svg"
    }, {
        id: "33",
        url: "icons/avatar/avatar1033.svg"
    }, {
        id: "34",
        url: "icons/avatar/avatar1034.svg"
    }, {
        id: "35",
        url: "icons/avatar/avatar1035.svg"
    }, {
        id: "36",
        url: "icons/avatar/avatar1036.svg"
    }, {
        id: "37",
        url: "icons/avatar/avatar1037.svg"
    }, {
        id: "38",
        url: "icons/avatar/avatar1038.svg"
    }, {
        id: "39",
        url: "icons/avatar/avatar1039.svg"
    }, {
        id: "40",
        url: "icons/avatar/avatar1040.svg"
    }, {
        id: "41",
        url: "icons/avatar/avatar1041.svg"
    }, {
        id: "42",
        url: "icons/avatar/avatar1042.svg"
    }, {
        id: "43",
        url: "icons/avatar/avatar1043.svg"
    }, {
        id: "44",
        url: "icons/avatar/avatar1044.svg"
    }, {
        id: "45",
        url: "icons/avatar/avatar1045.svg"
    }, {
        id: "46",
        url: "icons/avatar/avatar1046.svg"
    }, {
        id: "47",
        url: "icons/avatar/avatar1047.svg"
    }, {
        id: "48",
        url: "icons/avatar/avatar1048.svg"
    }, {
        id: "49",
        url: "icons/avatar/avatar1049.svg"
    }, {
        id: "50",
        url: "icons/avatar/avatar1050.svg"
    }, {
        id: "51",
        url: "icons/avatar/avatar1051.svg"
    }, {
        id: "52",
        url: "icons/avatar/avatar1052.svg"
    }, {
        id: "53",
        url: "icons/avatar/avatar1053.svg"
    }, {
        id: "54",
        url: "icons/avatar/avatar1054.svg"
    }, {
        id: "55",
        url: "icons/avatar/avatar1055.svg"
    }, {
        id: "56",
        url: "icons/avatar/avatar1056.svg"
    }, {
        id: "57",
        url: "icons/avatar/avatar1057.svg"
    }, {
        id: "58",
        url: "icons/avatar/avatar1058.svg"
    }, {
        id: "59",
        url: "icons/avatar/avatar1059.svg"
    }, {
        id: "60",
        url: "icons/avatar/avatar1060.svg"
    }, {
        id: "61",
        url: "icons/avatar/avatar1061.svg"
    }, {
        id: "62",
        url: "icons/avatar/avatar1062.svg"
    }, {
        id: "63",
        url: "icons/avatar/avatar1063.svg"
    }, {
        id: "64",
        url: "icons/avatar/avatar1064.svg"
    }, {
        id: "65",
        url: "icons/avatar/avatar1065.svg"
    }, {
        id: "66",
        url: "icons/avatar/avatar1066.svg"
    }, {
        id: "67",
        url: "icons/avatar/avatar1067.svg"
    }, {
        id: "68",
        url: "icons/avatar/avatar1068.svg"
    }, {
        id: "69",
        url: "icons/avatar/avatar1069.svg"
    }, {
        id: "70",
        url: "icons/avatar/avatar1070.svg"
    }, {
        id: "71",
        url: "icons/avatar/avatar1071.svg"
    }, {
        id: "72",
        url: "icons/avatar/avatar1072.svg"
    }, {
        id: "73",
        url: "icons/avatar/avatar1073.svg"
    }, {
        id: "74",
        url: "icons/avatar/avatar1074.svg"
    }, {
        id: "75",
        url: "icons/avatar/avatar1075.svg"
    }, {
        id: "76",
        url: "icons/avatar/avatar1076.svg"
    }, {
        id: "77",
        url: "icons/avatar/avatar1077.svg"
    }, {
        id: "78",
        url: "icons/avatar/avatar1078.svg"
    }, {
        id: "79",
        url: "icons/avatar/avatar1079.svg"
    }, {
        id: "80",
        url: "icons/avatar/avatar1080.svg"
    }, {
        id: "81",
        url: "icons/avatar/avatar1081.svg"
    }, {
        id: "82",
        url: "icons/avatar/avatar1082.svg"
    }, {
        id: "83",
        url: "icons/avatar/avatar1083.svg"
    }, {
        id: "84",
        url: "icons/avatar/avatar1084.svg"
    }, {
        id: "85",
        url: "icons/avatar/avatar1085.svg"
    }, {
        id: "86",
        url: "icons/avatar/avatar1086.svg"
    }, {
        id: "87",
        url: "icons/avatar/avatar1087.svg"
    }, {
        id: "88",
        url: "icons/avatar/avatar1088.svg"
    }, {
        id: "89",
        url: "icons/avatar/avatar1089.svg"
    }, {
        id: "90",
        url: "icons/avatar/avatar1090.svg"
    }, {
        id: "91",
        url: "icons/avatar/avatar1091.svg"
    }, {
        id: "92",
        url: "icons/avatar/avatar1092.svg"
    }, {
        id: "93",
        url: "icons/avatar/avatar1093.svg"
    }, {
        id: "94",
        url: "icons/avatar/avatar1094.svg"
    }, {
        id: "95",
        url: "icons/avatar/avatar1095.svg"
    }, {
        id: "96",
        url: "icons/avatar/avatar1096.svg"
    }, {
        id: "97",
        url: "icons/avatar/avatar1097.svg"
    }, {
        id: "98",
        url: "icons/avatar/avatar1098.svg"
    }, {
        id: "99",
        url: "icons/avatar/avatar1099.svg"
    }]

function getIcons() {
    return urlIcons;
}

module.exports = {
    getIcons
}